openapi: 3.0.0
info:
  title: Cryptomnio API
  version: 0.0.1
  contact:
    name: Flannel Division Support
    url: https://flanneldivision.com
    email: helloworld@flanneldivision.com
  x-logo:
    url: http://flanneldivision.com/img/FLDV_Full_Logo_Color.svg
  description: test
servers:
  - url: http://ec2-3-222-208-106.compute-1.amazonaws.com:{port}
    description: Staging Server
    variables:
      port:
        default: "8086"
  - url: https://api.samplehost.com/{version}
    description: Example dummy server
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
tags:
  - name: Keys
    description: CRUD operations for keys
  - name: Orders
    description: CRUD operations for orders.
  - name: Wallet
    description: CRUD operations for wallets
x-tagGroups:
  - name: Keys
    tags:
      - Keys
  - name: Orders
    tags:
      - Orders
  - name: Wallets
    tags:
      - Wallets
security:
  - Basic Auth: []
