=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/balance'
require 'openapi_client/models/currency_code'
require 'openapi_client/models/data_sync_allocation_level'
require 'openapi_client/models/error_message'
require 'openapi_client/models/exchange_code'
require 'openapi_client/models/inline_object'
require 'openapi_client/models/inline_object1'
require 'openapi_client/models/inline_object2'
require 'openapi_client/models/ok_message'
require 'openapi_client/models/order'
require 'openapi_client/models/pair_code'
require 'openapi_client/models/wallet'

# APIs
require 'openapi_client/api/keys_api'
require 'openapi_client/api/orders_api'
require 'openapi_client/api/wallets_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
