openapi: 3.0.0
info:
  title: Cryptomnio API
  version: 0.0.1
  contact:
    name: Flannel Division Support
    url: 'https://flanneldivision.com'
    email: helloworld@flanneldivision.com
  x-logo:
    url: 'https://cryptomnio.com/images/Cryptomnio_Logo_M.png'
  description: ''
servers:
  - url: 'http://ec2-3-222-208-106.compute-1.amazonaws.com:8086'
    description: Staging server
  - url: 'https://api.samplehost.com/{version}'
    description: Example dummy server
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
tags:
  - name: Keys
    description: CRUD operations for keys
  - name: Orders
    description: CRUD operations for orders.
  - name: Wallets
    description: CRUD operations for wallets
x-tagGroups:
  - name: Keys
    tags:
      - Keys
  - name: Orders
    tags:
      - Orders
  - name: Wallets
    tags:
      - Wallets
security:
  - BasicAuth: []
