=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::KeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeysApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::KeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeysApi' do
    it 'should create an instance of KeysApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::KeysApi)
    end
  end

  # unit tests for d_elete_keys_key_id_activation
  # Deactivate API key
  # Deactivates provided API key ID in Cryptomnio. This operation means that Cryptomnio will stop collecting data for the API key, but will keep current trading data in storage 
  # @param key_id 
  # @param [Hash] opts the optional parameters
  # @return [OkMessage]
  describe 'd_elete_keys_key_id_activation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for keys_key_id_delete
  # Deactivate and Delete API key
  # Deactivates and deletes API key from cryptomnio and clears all connected trade data (orders, balances, etc.) 
  # @param key_id 
  # @param [Hash] opts the optional parameters
  # @return [OkMessage]
  describe 'keys_key_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for keys_post
  # Upload and store exchange API key
  # Uploads and stores exchange API key in the cryptomnio.
  # @param inline_object 
  # @param [Hash] opts the optional parameters
  # @return [OkMessage]
  describe 'keys_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for p_ut_keys_key_id_activate
  # Activate API key
  # Activates stored API key in Cryptomnio. This operation means that Cryptomnio will start trading data synchronization  based on passed allocation level.  **NOTE** &#x60;Content-Length&#x60; will need to be set to zero when calling this endpoint.  For more information, this follows the style of  [github&#39;s API](https://developer.github.com/v3/gists/#star-a-gist) 
  # @param key_id 
  # @param inline_object1 
  # @param [Hash] opts the optional parameters
  # @return [OkMessage]
  describe 'p_ut_keys_key_id_activate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
