=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::OrdersApi)
    end
  end

  # unit tests for d_elete_orders_order_id
  # Cancel order
  # Cancels order on exchange and updates order status in Cryptomnio storage. This operation is allowed only if API key has been activated. 
  # @param order_id 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'd_elete_orders_order_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for g_et_orders
  # Get all orders
  # Returns all orders
  # @param [Hash] opts the optional parameters
  # @option opts [ExchangeCode] :exchange 
  # @option opts [String] :key_id API key ID
  # @option opts [Float] :internal_order_id Cryptomnio order ID
  # @option opts [Boolean] :closed_orders Get only closed orders
  # @option opts [Boolean] :active_orders Get only active orders
  # @return [Array<Order>]
  describe 'g_et_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for p_ost_orders
  # Create new order
  # Stores order in Cryptomnio and pushes it immediately to the exchange. The new order is stored with &#x60;queued&#x60; status, which means that order is being processed by the Cryptomnio. This operation is allowed only if API key has been activated. 
  # @param inline_object2 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'p_ost_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
