=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::WalletsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WalletsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::WalletsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WalletsApi' do
    it 'should create an instance of WalletsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::WalletsApi)
    end
  end

  # unit tests for wallets_get
  # Get all wallets
  # Get all wallets based on exchange
  # @param [Hash] opts the optional parameters
  # @option opts [ExchangeCode] :exchange 
  # @option opts [String] :key_id API key ID from cryptomnio
  # @return [Object]
  describe 'wallets_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wallets_wallet_id_get
  # Get wallet info
  # Get wallet info
  # @param wallet_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'wallets_wallet_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
