=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'date'

module OpenapiClient
  class CurrencyCode
    BTC = "btc".freeze
    LTC = "ltc".freeze
    ETH = "eth".freeze
    EUR = "eur".freeze
    USD = "usd".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CurrencyCode.constants.select { |c| CurrencyCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CurrencyCode" if constantValues.empty?
      value
    end
  end
end
