=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'date'

module OpenapiClient
  class DataSyncAllocationLevel
    TIER1 = "TIER1".freeze
    TIER2 = "TIER2".freeze
    TIER3 = "TIER3".freeze
    TIER4 = "TIER4".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DataSyncAllocationLevel.constants.select { |c| DataSyncAllocationLevel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DataSyncAllocationLevel" if constantValues.empty?
      value
    end
  end
end
