=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'date'

module OpenapiClient
  class ExchangeCode
    KRAKEN = "kraken".freeze
    BITFINEX = "bitfinex".freeze
    COINBASE = "coinbase".freeze
    GEMINI = "gemini".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ExchangeCode.constants.select { |c| ExchangeCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ExchangeCode" if constantValues.empty?
      value
    end
  end
end
