=begin
#Cryptomnio API

#test

The version of the OpenAPI document: 0.0.1
Contact: helloworld@flanneldivision.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'date'

module OpenapiClient
  class PairCode
    BTC_USD = "btc_usd".freeze
    BTC_EUR = "btc_eur".freeze
    ETH_USD = "eth_usd".freeze
    LTC_USD = "ltc_usd".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PairCode.constants.select { |c| PairCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PairCode" if constantValues.empty?
      value
    end
  end
end
